version: '3'
services:
  raspberry-status-server:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: stijink/raspberry-status-server
    working_dir: /var/www/
    command: nodemon index.js
    environment:
      - APP_PORT
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/var/www/
