version: '3'
services:
  raspberry-status-server:
    build: .
    image: stijink/raspberry-status-server
    working_dir: /var/www/
    command: pm2 start index.js --no-daemon --watch
    ports:
      - "9360:9360"
    volumes:
      - .:/var/www/
